export default [
    {
        id: 1,
        name: "cat1",
        title: "Rhea chilling on the couch",
        source: "/images/cat/cat1.jpg",
    },
    {
        id: 2,
        name: "cat2",
        title: "Rhea lazing around on the table",
        source: "/images/cat/cat2.jpg",
    },
    {
        id: 3,
        name: "cat3",
        title: "Rhea in the golden hour",
        source: "/images/cat/cat3.jpg",
    },
    {
        id: 4,
        name: "cat4",
        title: "Rhea and her favourite mushroom scratcher and fish toy",
        source: "/images/cat/cat4.jpg",
    },
    {
        id: 5,
        name: "cat5",
        title: "Rhea in her comfy bed",
        source: "/images/cat/cat5.jpg",
    },
    {
        id: 6,
        name: "cat6",
        title: "Rhea during the autumn season",
        source: "/images/cat/cat6.jpg",
    },
    {
        id: 7,
        name: "cat7",
        title: "Rhea cozying up next to white sunflowers",
        source: "/images/cat/cat7.jpg",
    }, 
    {
        id: 8,
        name: "cat8",
        title: "Rhea chilling on the kitchen table",
        source: "/images/cat/cat8.jpg",
    }, 
    {
        id: 9,
        name: "cat9",
        title: "Rhea and the rattan bag she loves to scratch",
        source: "/images/cat/cat9.jpg",
    }, 
    {
        id: 10,
        name: "cat10",
        title: "Fluffball Rhea",
        source: "/images/cat/cat10.jpg",
    }, 
    {
        id: 11,
        name: "cat11",
        title: "Rhea resting in her soft teddy bear house",
        source: "/images/cat/cat11.jpg",
    }, 
    {
        id: 12,
        name: "cat12",
        title: "The cutest Rhea",
        source: "/images/cat/cat12.jpg",
    },
    {
        id: 13,
        name: "cat13",
        title: "Rhea chilling in her checkered cardboard house",
        source: "/images/cat/cat13.jpg",
    },
    {
        id: 14,
        name: "cat14",
        title: "Rhea cozying up on the couch in the evening",
        source: "/images/cat/cat14.jpg",
    },
    {
        id: 15,
        name: "cat15",
        title: "Rhea getting ready for bed",
        source: "/images/cat/cat15.jpg",
    },
    {
        id: 16,
        name: "cat16",
        title: "Rhea as a cute piece of toast",
        source: "/images/cat/cat16.jpg",
    },
    {
        id: 17,
        name: "cat17",
        title: "Crescent moon Rhea",
        source: "/images/cat/cat17.jpg",
    },
    {
        id: 18,
        name: "cat18",
        title: "Rhea patiently waiting for me to feed her treats",
        source: "/images/cat/cat18.jpg",
    },
    {
        id: 19,
        name: "cat19",
        title: "Rhea sitting in her favourite spot in my desk chair",
        source: "/images/cat/cat19.jpg",
    },
    {
        id: 20,
        name: "cat20",
        title: "Rhea in her fuzzy checkered cat tunnel",
        source: "/images/cat/cat20.jpg",
    },
    {
        id: 21,
        name: "cat21",
        title: "Rhea playing with her favourite plush fish toy",
        source: "/images/cat/cat21.jpg",
    },
    {
        id: 22,
        name: "cat22",
        title: "Rhea chilling on the fluffy carpet",
        source: "/images/cat/cat22.jpg",
    },
    {
        id: 23,
        name: "cat23",
        title: "Rhea in the autumn season",
        source: "/images/cat/cat23.jpg",
    },
    {
        id: 24,
        name: "cat24",
        title: "Rhea debugging her code",
        source: "/images/cat/cat24.jpg",
    },
    {
        id: 25,
        name: "cat25",
        title: "Rhea enjoying the sunlight",
        source: "/images/cat/cat25.jpg",
    },
    {
        id: 26,
        name: "cat26",
        title: "Rhea's birthday celebration",
        source: "/images/cat/cat26.jpg",
    },
    {
        id: 27,
        name: "cat27",
        title: "Rhea hungry for her birthday cake",
        source: "/images/cat/cat27.jpg",
    },
    {
        id: 28,
        name: "cat28",
        title: "Rhea chilling in her cat tree",
        source: "/images/cat/cat28.jpg",
    },
    {
        id: 29,
        name: "cat29",
        title: "Rhea full of curiosity",
        source: "/images/cat/cat29.jpg",
    },
    {
        id: 30,
        name: "cat30",
        title: "Rhea basking in the glow of a beautiful sunset",
        source: "/images/cat/cat30.jpg",
    },
    {
        id: 31,
        name: "cat31",
        title: "Rhea enjoying her cozy new bed",
        source: "/images/cat/cat31.jpg",
    },
    {
        id: 32,
        name: "cat32",
        title: "Rhea perched on her cat tree",
        source: "/images/cat/cat32.jpg",
    },
    {
        id: 33,
        name: "cat33",
        title: "Pochacco Rhea",
        source: "/images/cat/cat33.jpg",
    },
    {
        id: 34,
        name: "cat34",
        title: "Rhea wearing a taiyaki hat",
        source: "/images/cat/cat34.jpg",
    },
    {
        id: 35,
        name: "cat35",
        title: "Rhea hiding behind the bamboo tree",
        source: "/images/cat/cat35.jpg",
    },
]