export default [
    {
        id: 1,
        name: "arashiyama",
        title: "Arashiyama Bamboo Forest, Kyoto, Japan",
        source: "/images/travel/arashiyama.jpg",
    },
    {
        id: 2,
        name: "bridal-falls",
        title: "Bridal Falls, BC, Canada",
        source: "/images/travel/bridal-falls.jpg",
    },
    {
        id: 3,
        name: "cabo-arch",
        title: "Cabo San Lucas Arch, Mexico",
        source: "/images/travel/cabo-arch.jpg",
    },
    {
        id: 4,
        name: "cabo-san-jose",
        title: "Cabo San Jose, Mexico",
        source: "/images/travel/cabo-san-jose.jpg",
    },
    {
        id: 5,
        name: "cabo",
        title: "Cabo Sunset, Mexico",
        source: "/images/travel/cabo.jpg",
    },
    {
        id: 6,
        name: "english-bay",
        title: "English Bay Sunset, BC, Canada",
        source: "/images/travel/english-bay.jpg",
    },
    {
        id: 7,
        name: "fushimi-inari",
        title: "Fushimi Inari Shrine, Kyoto, Japan",
        source: "/images/travel/fushimi.jpg",
    }, 
    {
        id: 8,
        name: "halcyon",
        title: "Halcyon Hot Springs, BC, Canada",
        source: "/images/travel/halcyon.jpg",
    }, 
    {
        id: 9,
        name: "harrison",
        title: "Harrison Hot Springs, BC, Canada",
        source: "/images/travel/harrison.jpg",
    }, 
    {
        id: 10,
        name: "inukshuk",
        title: "Inukshuk at Sunset Beach, BC, Canada",
        source: "/images/travel/inukshuk.jpg",
    }, 
    {
        id: 11,
        name: "lake-louise",
        title: "Lake Louise, Alberta, Canada",
        source: "/images/travel/lake-louise.jpg",
    }, 
    {
        id: 12,
        name: "nakano",
        title: "Nakano Broadway, Tokyo, Japan",
        source: "/images/travel/nakano.jpg",
    }, 
    {
        id: 13,
        name: "osaka-castle",
        title: "Osaka Castle, Osaka, Japan",
        source: "/images/travel/osaka-castle.jpg",
    }, 
    {
        id: 14,
        name: "seattle-market",
        title: "Seattle Market, Washington, USA",
        source: "/images/travel/seattle-market.jpg",
    }, 
    {
        id: 15,
        name: "shinjuku-garden",
        title: "Shinjuku Gyoen Garden, Tokyo, Japan",
        source: "/images/travel/shinjuku-garden.jpg",
    }, 
    {
        id: 16,
        name: "space-needle",
        title: "Seattle Space Needle, Washington, USA",
        source: "/images/travel/space-needle.jpg",
    }, 
    {
        id: 17,
        name: "toronto",
        title: "Nathan Phillips Square, Toronto, Canada",
        source: "/images/travel/toronto.jpg",
    }, 
    
]