export default [
    {
        id: 1,
        name: "arashiyama",
        title: "Arashiyama Bamboo Forest, Kyoto, Japan",
        source: "/images/travel/arashiyama.jpg",
    },
    {
        id: 2,
        name: "bridal-falls",
        title: "Bridal Falls, BC, Canada",
        source: "/images/travel/bridal-falls.jpg",
    },
    {
        id: 3,
        name: "cabo-arch",
        title: "Cabo San Lucas Arch, Mexico",
        source: "/images/travel/cabo-arch.jpg",
    },
    {
        id: 4,
        name: "cabo-san-jose",
        title: "Cabo San José, Mexico",
        source: "/images/travel/cabo-san-jose.jpg",
    },
    {
        id: 5,
        name: "cabo",
        title: "Sunset in Cabo San Lucas, Mexico",
        source: "/images/travel/cabo.jpg",
    },
    {
        id: 6,
        name: "english-bay",
        title: "English Bay Sunset, BC, Canada",
        source: "/images/travel/english-bay.jpg",
    },
    {
        id: 7,
        name: "fushimi-inari",
        title: "Fushimi Inari Shrine, Kyoto, Japan",
        source: "/images/travel/fushimi.jpg",
    }, 
    {
        id: 8,
        name: "halcyon",
        title: "Halcyon Hot Springs, BC, Canada",
        source: "/images/travel/halcyon.jpg",
    }, 
    {
        id: 9,
        name: "harrison",
        title: "Harrison Hot Springs, BC, Canada",
        source: "/images/travel/harrison.jpg",
    }, 
    {
        id: 10,
        name: "inukshuk",
        title: "Inukshuk at Sunset Beach, BC, Canada",
        source: "/images/travel/inukshuk.jpg",
    }, 
    {
        id: 11,
        name: "lake-louise",
        title: "Lake Louise, Alberta, Canada",
        source: "/images/travel/lake-louise.jpg",
    }, 
    {
        id: 12,
        name: "nakano",
        title: "Nakano Broadway, Tokyo, Japan",
        source: "/images/travel/nakano.jpg",
    }, 
    {
        id: 13,
        name: "osaka-castle",
        title: "Osaka Castle, Osaka, Japan",
        source: "/images/travel/osaka-castle.jpg",
    }, 
    {
        id: 14,
        name: "seattle-market",
        title: "Seattle Market, Washington, USA",
        source: "/images/travel/seattle-market.jpg",
    }, 
    {
        id: 15,
        name: "shinjuku-garden",
        title: "Shinjuku Gyoen Garden, Tokyo, Japan",
        source: "/images/travel/shinjuku-garden1.jpg",
    }, 
    {
        id: 16,
        name: "space-needle",
        title: "Seattle Space Needle, Washington, USA",
        source: "/images/travel/space-needle.jpg",
    }, 
    {
        id: 17,
        name: "toronto",
        title: "Nathan Phillips Square, Toronto, Canada",
        source: "/images/travel/toronto.jpg",
    }, 
    {
        id: 18,
        name: "imperial-palace",
        title: "Imperial Palace, Tokyo, Japan",
        source: "/images/travel/imperial-palace.jpg",
    }, 
    {
        id: 19,
        name: "emerald-lake1",
        title: "Emerald Lake, BC, Canada",
        source: "/images/travel/emerald-lake1.jpg",
    }, 
    {
        id: 20,
        name: "emerald-lake2",
        title: "Emerald Lake Lodge, BC, Canada",
        source: "/images/travel/emerald-lake2.jpg",
    },
    {
        id: 21,
        name: "harajuku",
        title: "Harajuku, Tokyo, Japan",
        source: "/images/travel/harajuku.jpg",
    },
    {
        id: 22,
        name: "disney-sea",
        title: "DisneySea, Tokyo, Japan",
        source: "/images/travel/disney-sea.jpg",
    }, 
    {
        id: 23,
        name: "kimono-forest",
        title: "Kimono Forest, Kyoto, Japan",
        source: "/images/travel/kimono-forest.jpg",
    }, 
    {
        id: 24,
        name: "natural-bridge",
        title: "Natural Bridge, BC, Canada",
        source: "/images/travel/natural-bridge.jpg",
    },
    {
        id: 25,
        name: "kinkakuji",
        title: "Kinaku-ji Golden Temple, Kyoto, Japan",
        source: "/images/travel/kinkakuji.jpg",
    },
    {
        id: 26,
        name: "team-labs-botanical1",
        title: "TeamLab Botanical Garden - Sculptures of Dissipative Birds in the Wind, Osaka, Japan",
        source: "/images/travel/team-labs-botanical1.jpg",
    }, 
    {
        id: 27,
        name: "petit-mura",
        title: "Petit Mura, Tokyo, Japan",
        source: "/images/travel/petit-mura.jpg",
    }, 
    {
        id: 28,
        name: "dontonburi",
        title: "Dotonbori, Osaka, Japan",
        source: "/images/travel/dotonbori.jpg",
    },
    {
        id: 29,
        name: "cabo-beach",
        title: "Cabos San Lucas Beach, Mexico",
        source: "/images/travel/cabo-beach.jpg",
    },
    {
        id: 30,
        name: "cabo-art-walk",
        title: "Cabos San Lucas Art Walk, Mexico",
        source: "/images/travel/cabo-art-walk.jpg",
    }, 
    {
        id: 31,
        name: "ghibli-museum",
        title: "Ghibli Museum, Tokyo, Japan",
        source: "/images/travel/ghibli-museum.jpg",
    }, 
    {
        id: 32,
        name: "sunflower-festival",
        title: "Sunflower Festival, BC, Canada",
        source: "/images/travel/sunflower-festival.jpg",
    },
    {
        id: 33,
        name: "arashiyama-river",
        title: "Arashiyama River, Kyoto, Japan",
        source: "/images/travel/arashiyama-river.jpg",
    },
    {
        id: 34,
        name: "team-labs-botanical2",
        title: "TeamLab Botanical Garden - Floating Resonating Lamps on Oike Lake, Osaka, Japan",
        source: "/images/travel/team-labs-botanical2.jpg",
    }, 
    {
        id: 35,
        name: "urayasu-onsen",
        title: "Urayasu Onsen, Tokyo, Japan",
        source: "/images/travel/urayasu-onsen.jpg",
    },
    {
        id: 36,
        name: "shibuya-sky",
        title: "Shibuya Sky, Tokyo, Japan",
        source: "/images/travel/shibuya-sky.jpg",
    },
    {
        id: 37,
        name: "shinjuku-garden2",
        title: "Shinjuku Gyoen Garden, Tokyo, Japan",
        source: "/images/travel/shinjuku-garden2.jpg",
    }, 
    {
        id: 38,
        name: "inokashira-park",
        title: "Inokashira Park, Tokyo, Japan",
        source: "/images/travel/inokashira-park.jpg",
    },
    {
        id: 39,
        name: "kiyomizu-dera",
        title: "Kiyo-mizu Dera Temple, Kyoto, Japan",
        source: "/images/travel/kiyomizu-dera.jpg",
    },
]